<!-- Generate from https://realfavicongenerator.net/ -->
<link rel="apple-touch-icon" sizes="180x180" href="/themes/THEME-NAME/assets/dist/images/icons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/themes/THEME-NAME/assets/dist/images/icons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/themes/THEME-NAME/assets/dist/images/icons/favicon-16x16.png">
<link rel="mask-icon" href="/themes/THEME-NAME/assets/dist/images/icons/safari-pinned-tab.svg" color="#5bbad5">
<link rel="shortcut icon" href="/themes/THEME-NAME/assets/dist/images/icons/favicon.png">
<meta name="msapplication-TileColor" content="#00aba9">
<meta name="msapplication-config" content="/themes/THEME-NAME/assets/dist/images/icons/browserconfig.xml">
<meta name="theme-color" content="#ffffff">